spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/load_balancing_back?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

    open-in-view: false
